# Generated by Django 5.2.8 on 2025-11-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Bozza'), (1, 'Pubblicato'), (2, 'Archiviato'), (3, 'Cancellato')], default=0),
        ),
    ]
