# Generated by Django 5.2.8 on 2025-11-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Bozza'), (1, 'Pubblicato'), (2, 'Archiviato')], default=0),
        ),
    ]
